### ISSUE TITLE
Plugin references a non-existent class and file

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/EDD-External-Products#3]
![image](https://cloud.githubusercontent.com/assets/1254870/12690780/ef4e0560-c6b3-11e5-8748-444ff7c340b0.png)

Neither the class nor the file exist. 

Reference: https://github.com/easydigitaldownloads/EDD-External-Products/blob/master/edd-external-products.php#L236-L240

@ghost1227 can you get this sorted out and tagged for release?

**Comment by ghost1227** [comment]
Fixed in 1.1.0
